#pragma once
#include "CTransform.h"
#include "CMeshRenderer.h"
#include "CSpriteRenderer.h"
#include "CCollider2D.h"
#include "CRenderComponent.h"
#include "CBillboardRenderer.h"
#include "CCamera.h"
#include "CTileRenderer.h"
#include "CFlipbookRenderer.h"
#include "CLight2D.h"
// #include "CBillboardRender.h"
// #include "CLight3D.h"
// #include "CMeshrenderer.h"
// #include "CParticleRender.h"
// #include "CSpriterenderer.h"
#include "CScript.h"
#include "Source\Scripts\CAtlasAnimator.h"
